SideBar new
DevBuffProject/DevBuff-frontend-next pull request #42
Opened 2022-04-12 11:34 UTC by Roseskk

Need Review

2022-04-12 16:05 UTC, BigTows requested changes
В целом нужно проработать моменты:
 * Минимум наших SVG (Нужно переиспользовать, SVG это такой же код)
 * Все ресурсы в public

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/header/Header.js
Да можно удалить в принципе

2022-04-12 16:05 UTC, BigTows commented on src/styles/globals.css
> +  src: url("../fonts/Montserrat-Regular.ttf") format('truetype');
А может все ресурсы в `public`?

2022-04-12 16:05 UTC, BigTows commented on src/pages/explore/[page].js
> +import {Helmet} from "react-helmet";
unused

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/user_menu/side_menu/SideMenu.js
> +                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
Либо SVG в файлы или из либы, так оставлять не очень хорошо, нагружает код.

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/user_menu/side_ideas/SideIdeas.js
> +                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
SVG в ресурсы

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/user_menu/side_ideas/SideIdeas.js
> +                        <Image src={'/images/arrow-up.gif'} width={20} height={20} />
Надо поискать замену гифкам, а то кринж какой-то
![13887749957245](https://user-images.githubusercontent.com/9078504/163004731-4f69bd30-6db6-47f7-bd5f-528fcd128c4f.gif)

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/user_menu/UserMenu.js
> +            <SideIdeas />
Тут нужен будет флаг на авторизацию

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/authorization/LoggedUser.js
> +                                <Image src={'/images/arrow-up.gif'} width={20} height={20} />
Гифффка

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/authorization/LoggedUser.js
> +    console.log(profile)
here

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/authorization/Authorization.js
> +                            <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor"
SVG -> в ресурсы

2022-04-12 16:05 UTC, BigTows commented on src/components/composed/navigation/navigation/authorization/Authorization.js
> +                        <Image src={'/images/gtL.svg'} width={30} height={30} />
Название должно быть более понятным

2022-04-12 18:24 UTC, BigTows approved these changes

2022-04-13 10:39 UTC, BigTows requested changes
Билд упал

2022-04-13 10:39 UTC, BigTows commented on src/components/composed/navigation/navigation/authorization/Authorization.js
> +                <button onClick={handleGITHUB} className={'w-full p-1 rounded bg-blue-300 backdrop-blur text-white font-montserratBold hover:bg-blue-500 transition ease-in-out duration-500'}>GITHUB</
Code style метода

2022-04-13 10:39 UTC, BigTows commented on src/components/composed/navigation/navigation/authorization/LoggedUser.js
> +                                    <Image src={`${baseUrl}/photo/profile/${profile.id}`} width={32} height={32} />
Я думаю надо URL поменять на бизнес слой (TODO)

2022-04-13 12:46 UTC, BigTows approved these changes

2022-04-13 13:12 UTC, Roseskk commented on src/components/composed/header/Header.js
пока пусть будет он еще нужен

2022-04-13 13:12 UTC, BigTows commented on src/components/composed/navigation/navigation/user_menu/UserMenu.js
> +import {FaFontAwesome, FaUser, FaUserCircle, FaUserCog} from "react-icons/fa";
Fa? если не нужен то удалить его из package.json

2022-04-13 13:12 UTC, Roseskk commented on src/styles/globals.css
> +  src: url("../fonts/Montserrat-Regular.ttf") format('truetype');
Шрифты по документации должны быть тут

2022-04-13 13:12 UTC, Roseskk commented on src/pages/explore/[page].js
> +import {Helmet} from "react-helmet";
Уже юзаю

2022-04-13 13:13 UTC, Roseskk commented on src/components/composed/navigation/navigation/user_menu/UserMenu.js
> +import {FaFontAwesome, FaUser, FaUserCircle, FaUserCog} from "react-icons/fa";
удалим

2022-04-13 13:14 UTC, merged