ideas design + ...sticky sidebar
DevBuffProject/DevBuff-frontend-next pull request #65
Opened 2022-04-16 11:58 UTC by Roseskk

2022-04-16 18:38 UTC, BigTows requested changes

2022-04-16 18:38 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaCard.js
> +                               <span className={'font-montserratThin text-xs'}>{new Date(idea.publishDate).toDateString()}</span>
Time ago

2022-04-16 18:38 UTC, BigTows commented on src/pages/explore/[page].tsx
> +    // const [idea, setIdea] = useState({})
Убрать комменты

2022-04-16 18:38 UTC, BigTows commented on src/services/idea/IdeaService.ts
> +        return this.api.getIdeas(1, SortType.Date)
Передавать параметры в метод.

2022-04-16 18:38 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Languages.js
> +                    lang.map((requirements,idx)=>{
мб как-то проще можно ;/

2022-04-16 18:44 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Languages.js
> +                    lang.map((requirements,idx)=>{
Добавить hashSet на все

2022-04-16 18:45 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Languages.js
> +                    lang.map((requirements,idx)=>{
+ Если пусто, не нужно выводить пункт меню

2022-04-16 18:46 UTC, BigTows commented
Не хватает пагинации.

2022-04-18 13:30 UTC, BigTows requested changes

2022-04-18 13:30 UTC, BigTows commented on package.json
> +    "underscore": "^1.13.2"
А тут оно нужно?

2022-04-18 13:30 UTC, BigTows commented on src/services/utility/UtilityService.ts
> +        const uniq = new Set(arr.map(e => JSON.stringify(e)));
Калхоз какой-то

2022-04-18 13:30 UTC, BigTows commented on src/services/utility/UtilityService.ts
> +    public removeDupedItemArray(arr : Array<any>) : Array<any> {
Можно сделать методы статичесикими, потому что у тебя нету состояния, это чисто класс ради алгоритма

2022-04-18 13:30 UTC, BigTows commented on src/config/DependencyInjection.ts
> +    {provide: UtilityService, useClass: UtilityService, deps: []},
Можно без экземпляра

2022-04-18 13:30 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Specialists.js
> +                service.removeDupedItemObject(specialist).map((spec,idx)=>{
https://stackoverflow.com/questions/9229645/remove-duplicate-values-from-js-array
 Может в этом направлении подумать, я просто не помню структуру данных

2022-04-18 13:30 UTC, BigTows commented
И почему-то 500
https://deploy-preview-65--cheerful-lily-b65942.netlify.app/explore/1

2022-04-18 13:36 UTC, Roseskk commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Specialists.js
> +                service.removeDupedItemObject(specialist).map((spec,idx)=>{
у нас массив объектов , по этому так сделал

2022-04-18 13:36 UTC, Roseskk commented on src/services/utility/UtilityService.ts
> +        const uniq = new Set(arr.map(e => JSON.stringify(e)));
да ну

2022-04-18 13:36 UTC, Roseskk commented on package.json
> +    "underscore": "^1.13.2"
не тесты были

2022-04-18 13:44 UTC, Roseskk commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Languages.js
> +                    lang.map((requirements,idx)=>{
я хз как проще просто

2022-04-18 14:10 UTC, Roseskk commented on src/services/idea/IdeaService.ts
> +        return this.api.getIdeas(1, SortType.Date)
это другой тикет где пагинация будет я думаю

2022-04-19 18:27 UTC, BigTows requested changes

2022-04-19 18:27 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaCard.tsx
> +                                   <span>Специалисты</span>
Если нет специалистов, не показывать

2022-04-19 18:27 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaCard.tsx
> +                                   <span>Технологии</span>
Если нет технологий, не показывать

2022-04-19 18:27 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaCard.tsx
> +                                   <span>Языки программирования</span>
Если нет ЯП не показывать

2022-04-19 18:27 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Specialists.tsx
> +                UtilityService.removeDupedSpecialistObject(params.specialist).map((spec,idx)=>{
map + filter 
Лады, да да

2022-04-19 18:27 UTC, BigTows commented on src/components/composed/ideas/constructor/idea_card/IdeaList/Tech.tsx
> +                params.tech.map((requirements)=>{
flatmap x2 + map + filter

2022-04-19 18:27 UTC, BigTows commented on src/pages/explore/[page].tsx
> +export const getServerSideProps: GetServerSideProps = async (context : any) => {
А тут может быть не any?

2022-04-19 18:27 UTC, BigTows commented on src/services/idea/IdeaService.ts
> +        return this.api.getIdeas(page, SortType.Date,[],[])
Добавить и остальные параметры

2022-04-19 18:27 UTC, BigTows commented on src/services/utility/UtilityService.ts
> +    static setColorLanguage(language : string | undefined) : string {
либо на back либо в random hex

2022-04-19 18:27 UTC, BigTows commented on src/services/utility/objects/SpecialistsType.ts
> +    name : string | undefined
Удалить - (@Roseskk)

2022-04-20 14:23 UTC, Roseskk commented on src/services/utility/UtilityService.ts
> +    static setColorLanguage(language : string | undefined) : string {
Решим

2022-04-20 15:52 UTC, BigTows approved these changes

2022-04-20 15:54 UTC, merged