34 оформление страницы персональная страница пользователя
DevBuffProject/DevBuff-frontend-next pull request #68
Opened 2022-04-22 16:00 UTC by Roseskk

2022-04-22 16:00 UTC, BigTows commented
Wow

2022-04-22 16:06 UTC, BigTows requested changes

2022-04-22 16:06 UTC, BigTows commented on src/api/file/FileApi.ts
> +     public getUserAvatar (uuid: string | undefined ): string {
Зачем?

2022-04-22 16:06 UTC, BigTows commented on src/components/composed/users/UserForm.js
> +        <div className={'flex gap-1'}>
Переместить в другое место к примеру SideBar

2022-04-22 16:06 UTC, BigTows commented on src/pages/users/[userId].tsx
> +                            <span className={''}>{!user?.countryId ? 'Country' : user.countryId}</span>
Вот на это можно забить, рудимент

2022-04-22 16:06 UTC, BigTows commented on src/services/profile/ProfileService.ts
> +    public getAvatar(uuid : string | undefined ): string {
Зачем?

2022-04-24 09:53 UTC, Roseskk commented on src/api/file/FileApi.ts
> +     public getUserAvatar (uuid: string | undefined ): string {
по другому не работает, потому что если ввести неверный id пользователя то будет undefined

2022-04-24 09:53 UTC, Roseskk commented on src/services/profile/ProfileService.ts
> +    public getAvatar(uuid : string | undefined ): string {
уже написал

2022-04-24 09:53 UTC, Roseskk commented on src/pages/users/[userId].tsx
> +                            <span className={''}>{!user?.countryId ? 'Country' : user.countryId}</span>
а как не через тернарный оператор вывести это

2022-04-24 19:37 UTC, BigTows approved these changes

2022-04-24 19:38 UTC, BigTows commented on src/pages/users/[userId].tsx
> +                            <span className={''}>{!user?.countryId ? 'Country' : user.countryId}</span>
Не я про сами данные)

2022-04-24 19:38 UTC, BigTows commented on src/api/file/FileApi.ts
> +     public getUserAvatar (uuid: string | undefined ): string {
А зачем вызывать этот метод, если что-то undefined?

2022-04-25 13:35 UTC, BigTows commented
Ага

2022-04-25 16:48 UTC, BigTows requested changes

2022-04-25 16:48 UTC, BigTows commented on src/components/composed/users/SelfIdeas.tsx
> +        ideaService.getIdeasSelf()
Наверное так нельзя, потому что будет показываться идеи текущего пользователя

2022-04-25 16:48 UTC, BigTows commented on src/components/composed/users/Skill.tsx
> +    return(
Поделить на функции

2022-04-25 16:48 UTC, BigTows commented on src/components/composed/users/Skill.tsx
> +                                        skillName.specializations?.map((specializationName,idx)=>{
specializations всегда должен быть массивом

2022-04-25 16:48 UTC, BigTows commented on src/pages/users/[userId].tsx
>      if (profileResult.profile === undefined) {
Надо как-то продумать этот момент

2022-04-25 16:48 UTC, BigTows commented on src/components/composed/users/Profile.tsx
> +                    <span className={''}>{!user?.countryId ? 'Country' : user.countryId}</span>
Убрать страну и город

2022-04-26 09:35 UTC, Roseskk commented
Еще не все

2022-04-26 14:29 UTC, BigTows requested changes

2022-04-26 14:29 UTC, BigTows commented on src/api/idea/IdeaApi.ts
> +    public async getOwnerIdeas(ownerUUID: string) : Promise<Array<OwnerIdea>> {
Пробелы)

2022-04-26 14:29 UTC, BigTows commented on src/components/composed/users/SelfIdeas.tsx
> +            .then((result:any) =>setIdeas(result))
Не any

2022-04-27 09:46 UTC, BigTows approved these changes

2022-04-27 09:48 UTC, merged