77 страница идеи
DevBuffProject/DevBuff-frontend-next pull request #78
Opened 2022-05-11 09:55 UTC by Roseskk

Hydration failed (React html renderer)

2022-05-12 09:10 UTC, BigTows requested changes

2022-05-12 09:10 UTC, BigTows commented on src/components/composed/idea/constructor/IdeaProfile.tsx
> +export default  function IdeaProfile() {
IdeaHeader или IdeaInformation что-то такое

2022-05-12 09:10 UTC, BigTows commented on src/pages/idea/explore/[id].tsx
> +    const idea_id = context.query.id;
ideaId

2022-05-12 09:10 UTC, BigTows commented on src/pages/idea/explore/[id].tsx
> +import {GetServerSidePropsContext} from "next/types";
![image](https://user-images.githubusercontent.com/9078504/168035328-629a2ad9-ac28-4801-92fa-aaaafc5e8316.png)

2022-05-12 09:10 UTC, BigTows commented on src/pages/idea/explore/[id].tsx
> +import {GetServerSidePropsContext} from "next/types";
чем отличается /idea/uuid от /idea/explore/uuid?

2022-05-12 09:10 UTC, BigTows commented on src/pages/idea/explore/[id].tsx
> +                <p className={'font-montserratLight md:text-base text-xs'}>{renderHTML(idea.text)}</p>
Это во вкладке должно быть

2022-05-13 08:40 UTC, Roseskk commented on src/pages/idea/explore/[id].tsx
> +                <p className={'font-montserratLight md:text-base text-xs'}>{renderHTML(idea.text)}</p>
Про какую вкалдку идет речь?

2022-05-17 20:50 UTC, BigTows approved these changes

2022-05-17 20:50 UTC, BigTows commented on src/pages/idea/explore/[ideaId].tsx
> +    const idea_id = context.query.ideaId;
codeStyle

2022-05-17 20:50 UTC, BigTows commented on src/pages/idea/explore/[ideaId].tsx
> +    console.log(idea)
here :)

2022-05-17 20:50 UTC, BigTows commented on package.json
> +    "react-render-html": "^0.6.0",
Вроде уже не нужно?

2022-05-17 20:50 UTC, BigTows commented on src/components/composed/idea/constructor/tab_constructor/TabBar.tsx
> +// import {useState} from "react";
Удолить

2022-05-17 20:50 UTC, BigTows commented on src/components/composed/idea/constructor/tab_constructor/TabBar.tsx
> +    // const [explore,SetExplore] = useState('border-b-0');
Удолить

2022-05-17 20:50 UTC, BigTows commented on src/pages/_app.tsx
> +// import IdeaPage from "./idea/[id]";
Удолить

2022-05-17 20:50 UTC, BigTows commented on src/pages/idea/[id].tsx
> +    console.log('123123123',id)
Удолить

2022-05-18 09:36 UTC, merged